apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: gcr.io/YOUR_PROJECT_ID/notes-app:latest  # Replace YOUR_PROJECT_ID
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret-key
        - name: JWT_REFRESH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-refresh-secret-key
        - name: LLAMA_APIKEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: llama-api-key
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openrouter-api-key
        - name: OPENROUTER_BASE_URL
          value: "https://openrouter.ai/api/v1"
        - name: EXA_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: exa-api-key
        - name: PAPERSWITHCODE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: paperswithcode-api-key
        - name: AWS_BUCKET_NAME
          value: "your-bucket-name"  # Replace with your bucket name
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: aws-secret-access-key
        - name: AWS_REGION
          value: "us-east-1"  # Replace with your region
        - name: REDIS_URL
          value: "redis://MEMORYSTORE_IP:6379"  # Replace with actual Memorystore IP
        - name: WEAVIATE_URL
          value: "http://weaviate-service:5000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: notes-app
spec:
  selector:
    app: fastapi
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer