version: '3.8'

services:


  fastapi:
    build:
      context: ./note-server     
      dockerfile: Dockerfile    
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - weaviate_anon
      # - elasticsearch
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - LLAMA_APIKEY=${LLAMA_APIKEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL}
      - EXA_API_KEY=${EXA_API_KEY}
      - PAPERSWITHCODE_API_KEY=${PAPERSWITHCODE_API_KEY}

    # volumes:
    #   - ./note-server:/app     

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  weaviate_anon:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.2
    command:
      - --host
      - 0.0.0.0
      - --port
      - '5000'
      - --scheme
      - http
    ports:
      - "5000:5000"
      - "50051:50051"
    restart: on-failure:0
    environment:
      LLAMA_APIKEY: ${LLAMA_APIKEY}
      # COHERE_APIKEY:
      # HUGGINGFACE_APIKEY: ${HUGGINGFACE_APIKEY}
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      AUTHENTICATION__OIDC__ENABLED: 'false'/
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-openai,generative-openai,generative-cohere'
      BACKUP_FILESYSTEM_PATH: '/var/lib/weaviate/backups'
      CLUSTER_HOSTNAME: 'cluster-init'
    volumes:
      - weaviate_data:/var/lib/weaviate
      - weaviate_backups:/var/lib/weaviate/backups

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.11.4
  #   container_name: kibana
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch

volumes:
  redis_data:
  weaviate_data:
  weaviate_backups:
  # elasticsearch_data:
